name: "Delete old artifacts"
on:
  schedule:
    - cron: "0 4 * * *" # every night at 4 am UTC
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove artifact
        uses: philips-labs/action-delete-artifacts@v1.0.0
        with:
          # Optional, GitHub token, a Personal Access Token with `repo` scope if needed
          # Required, if artifact is from a different repo
          # Required, if repo is private a Personal Access Token with `repo` scope is needed
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Required, workflow file name or ID
          workflow: test.yml
          # Optional, uploaded artifact name,
          # will delete all artifacts if not specified
          # name: cypresartifact
          workflow_conclusion: failure
