name: "Delete old artifacts"
on:
  schedule:
    - cron: "0 4 * * *" # every night at 4 am UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Weekly Artifact Cleanup
        uses: jimschubert/delete-artifacts-action@v1
        with:
          GITHUB_TOKEN: ${{secrets.ARTIFACT_CLEANUP_GITHUB_TOKEN}}
          log_level: 'error'
          min_bytes: '0'
          pattern: 'cypres'
